default: &default
  adapter: postgresql
  encoding: unicode
  pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>

development:
  <<: *default
  database: reciclaje_cristobalbarrera
  username: cristobal
  password: admin1234
  host: localhost
  port: 5432

test:
  <<: *default
  database: reciclaje_cristobalbarrera_test
  username: cristobal
  password: admin1234
  host: localhost
  port: 5432
